---
networks:
- name: vip
  type: vip
- name: default
  subnets:
  - range: 10.4.0.0/24
    gateway: 10.4.0.1
    cloud_properties:
      network_name: bosh-demo # <- your network name
      subnetwork_name: bosh-demo-infra # <- your global-infra-0 subnetwork name
      tags:
        - bosh-demo-default # <- your global-internal firewall name
    reserved:
      - 10.4.0.16 - 10.4.0.254 # Allocated to other deployments
    static:
      - 10.4.0.2

jobs:
- name: bosh
  networks:
  - (( prepend ))
  - name: vip
    static_ips: [104.155.48.8]
