---
name: nomad-deployment
director_uuid: 63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79

update:
  serial: false
  canaries: 1
  canary_watch_time: 10000-60000
  max_in_flight: 4
  update_watch_time: 10000-60000

releases:
- name: nomad
  version: latest
- name: consul
  version: latest
- name: docker
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3312.9

instance_groups:
- name: server
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: nomad-server
    release: nomad
  - name: nomad-ui
    release: nomad
  - name: consul
    release: consul
    provides:
      consul_servers: { as: consul }
    consumes:
      consul_servers: { from: consul }
  stemcell: default
  vm_type: server
  persistent_disk_pool: medium
  networks:
  - name: servers
  properties:
    consul:
      server: true
  update: { serial: true }

- name: node
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: nomad-client
    release: nomad
  - name: docker
    release: docker
  - name: consul
    release: consul
    consumes:
      consul_servers: { from: consul }
  stemcell: default
  vm_type: node
  persistent_disk_pool: medium
  networks:
  - name: nodes
  properties:
    nomad:
      docker:
        cleanup_image: false

properties:
  consul:
    leave_on_terminate: true
  nomad:
    leave_on_terminate: true
